name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version that will be downloaded
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ github.event.inputs.version }}"
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prefetch docker images
        run: |
          docker pull stelzo/swf-to-svg:latest
          docker pull stelzo/svg-to-png:latest
          docker pull stelzo/doduda-umbu:latest
          docker pull stelzo/assetstudio-cli:latest
      - name: Get doduda
        run: |
          sudo apt-get install curl wget -y
          curl -s https://api.github.com/repos/dofusdude/doduda/releases/latest \
              | grep "browser_download_url.*Linux_x86_64.tar.gz" \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | wget -qi -
          tar -xzf "doduda_Linux_x86_64.tar.gz"
          rm "doduda_Linux_x86_64.tar.gz"
          chmod +x doduda
          ./doduda --version
          pwd
      - name: Download
        run: ./doduda --headless --release beta --dofus-version ${{ github.event.inputs.version }} --output ./data
      - name: Package
        run: |
          mkdir out

          mv data/*.json out/
          mv data/languages/*.json out/

          tar -czf items_images_64.tar.gz $(find data/img/item/1x -name "*.png")
          mv items_images_64.tar.gz out/

          tar -czf items_images_128.tar.gz $(find data/img/item/2x -name "*.png")
          mv items_images_128.tar.gz out/
      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ github.event.inputs.version }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          files: out/*
      - name: Notify doduapi to update
        run: |
          curl -X POST \
          https://api.dofusdu.de/dofus3beta/update/${{ secrets.DODUAPI_TOKEN }} \
          -d '{"version":"${{ github.event.inputs.version }}"}'
